gitops-runtime:
  global:
    codefresh:
      accountId: 6764c747996f75deae76f97a
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: codefresh
      isConfigurationRuntime: true
